<?php

namespace OrigamiMp\OrigamiApiSdk\Exceptions\Dtos\User\UserGroupInvitation;

use OrigamiMp\OrigamiApiSdk\Exceptions\Dtos\ApiResponseDtoNotConstructableException;

class UserGroupInvitationCheckPendingResponseDtoNotConstructableException extends ApiResponseDtoNotConstructableException {}
