<?php

namespace OrigamiMp\OrigamiApiSdk\Exceptions\Dtos\User;

use OrigamiMp\OrigamiApiSdk\Exceptions\Dtos\ApiResponseDtoNotConstructableException;

class UserGroupInvitationCancelResponseDtoNotConstructableException extends ApiResponseDtoNotConstructableException {}
