<?php

namespace OrigamiMp\OrigamiApiSdk\Exceptions\Dtos\User;

use OrigamiMp\OrigamiApiSdk\Exceptions\Dtos\ApiResponseDtoNotConstructableException;

class UserGroupInvitationResendResponseDtoNotConstructableException extends ApiResponseDtoNotConstructableException {}
