name: Laravel Pint

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pint:
    runs-on: ubuntu-latest
    name: Laravel Pint check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - name: Get changed files (only php files)
#        id: changed-files
#        uses: tj-actions/changed-files@v46
#        with:
#          files: |
#            **/*.php
#
#      - name: List all changed files (only php files)
#        run: |
#          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
#            echo "$file was changed"
#          done

      - name: Setup nightly PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, redis
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: php-cs-fixer, phpunit

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Laravel pint
#        if: steps.changed-files.outputs.all_changed_files
        run: ./vendor/bin/pint --test -v